New log file opened at Sun May 10 15:11:16 CEST 2015 by 6028@Admin-PC
Taking next connection to: 54214
New client attempting to connect on port: 54215-54214
  Address = /192.168.0.10:54214
This client on port 54215 has uuid dc591679-c2bb-425b-ab7d-2d76bbb682ad configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-dc591679-c2bb-425b-ab7d-2d76bbb682ad
Taking next connection to: 54214
New client attempting to connect on port: 54216-54214
  Address = /192.168.0.10:54214
Handshake exception on socket: 54216
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 54214
New client attempting to connect on port: 54217-54214
  Address = /192.168.0.10:54214
This client on port 54217 has uuid b3bc08cb-e1b1-4dd2-a3cb-ce05d3f730a7 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-dc591679-c2bb-425b-ab7d-2d76bbb682ad, activator-b3bc08cb-e1b1-4dd2-a3cb-ce05d3f730a7
Taking next connection to: 54214
New client attempting to connect on port: 54218-54214
  Address = /192.168.0.10:54214
Handshake exception on socket: 54218
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 54214
New client attempting to connect on port: 54219-54214
  Address = /192.168.0.10:54214
This client on port 54219 has uuid 410fff4a-031d-4e23-a27a-dc93ed57690e configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-dc591679-c2bb-425b-ab7d-2d76bbb682ad, activator-b3bc08cb-e1b1-4dd2-a3cb-ce05d3f730a7, play-fork-run-410fff4a-031d-4e23-a27a-dc93ed57690e
Taking next connection to: 54214
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54214
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54214
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54214
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54214
