New log file opened at Mon May 04 00:26:50 CEST 2015 by 1464@Admin-PC
Taking next connection to: 51221
New client attempting to connect on port: 51222-51221
  Address = /192.168.0.10:51221
This client on port 51222 has uuid a681cc26-8800-46ea-b4dd-8a072bd425ec configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-a681cc26-8800-46ea-b4dd-8a072bd425ec
Taking next connection to: 51221
New client attempting to connect on port: 51223-51221
  Address = /192.168.0.10:51221
Handshake exception on socket: 51223
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51221
New client attempting to connect on port: 51224-51221
  Address = /192.168.0.10:51221
This client on port 51224 has uuid 497ebdb2-a00e-4a29-9b68-bf1aa5d24ff5 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-a681cc26-8800-46ea-b4dd-8a072bd425ec, activator-497ebdb2-a00e-4a29-9b68-bf1aa5d24ff5
Taking next connection to: 51221
New client attempting to connect on port: 51225-51221
  Address = /192.168.0.10:51221
Handshake exception on socket: 51225
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51221
New client attempting to connect on port: 51226-51221
  Address = /192.168.0.10:51221
This client on port 51226 has uuid 197d80fc-9cec-424c-84c6-560a47704e8f configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-a681cc26-8800-46ea-b4dd-8a072bd425ec, activator-497ebdb2-a00e-4a29-9b68-bf1aa5d24ff5, activator-197d80fc-9cec-424c-84c6-560a47704e8f
Taking next connection to: 51221
New client attempting to connect on port: 51227-51221
  Address = /192.168.0.10:51221
Handshake exception on socket: 51227
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51221
New client attempting to connect on port: 51228-51221
  Address = /192.168.0.10:51221
This client on port 51228 has uuid fda7f4b8-c3e8-4742-bf68-5a14a1a5ce38 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-a681cc26-8800-46ea-b4dd-8a072bd425ec, activator-497ebdb2-a00e-4a29-9b68-bf1aa5d24ff5, activator-197d80fc-9cec-424c-84c6-560a47704e8f, activator-fda7f4b8-c3e8-4742-bf68-5a14a1a5ce38
Taking next connection to: 51221
New client attempting to connect on port: 51229-51221
  Address = /192.168.0.10:51221
Handshake exception on socket: 51229
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51221
New client attempting to connect on port: 51230-51221
  Address = /192.168.0.10:51221
This client on port 51230 has uuid 6ddc8801-1f56-40b0-985f-bc1e8ee09017 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-a681cc26-8800-46ea-b4dd-8a072bd425ec, activator-497ebdb2-a00e-4a29-9b68-bf1aa5d24ff5, activator-197d80fc-9cec-424c-84c6-560a47704e8f, activator-fda7f4b8-c3e8-4742-bf68-5a14a1a5ce38, activator-6ddc8801-1f56-40b0-985f-bc1e8ee09017
Taking next connection to: 51221
New client attempting to connect on port: 51261-51221
  Address = /192.168.0.10:51221
Handshake exception on socket: 51261
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51221
New client attempting to connect on port: 51262-51221
  Address = /192.168.0.10:51221
This client on port 51262 has uuid bad284f2-62d4-4d8b-91c1-edd786b69483 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-a681cc26-8800-46ea-b4dd-8a072bd425ec, activator-6ddc8801-1f56-40b0-985f-bc1e8ee09017, play-fork-run-bad284f2-62d4-4d8b-91c1-edd786b69483
Taking next connection to: 51221
Checking to see if clients are empty...
We have 2 non-daemon clients, continuing serving connections.
Taking next connection to: 51221
